---
title: "SIG/RIG Presentation - Demo Shiny App"
author: "KF"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	eval = FALSE
)
```

## Import

### Packages + Functions

```{r}
#Core packages/functions
gc()
library(tidyverse)
library(data.table)
library(readxl)
library(bslib)
library(here)

#Additional packages
library(shiny)
library(plotly)
```

### Data

```{r}
#titanic dataset
titanic <- read_csv(here("Sample Data/train.csv"))
```

## Shiny

### UI

```{r}
ui <- fluidPage(
  titlePanel("Shiny App Demo"),
  h4("By: KF"),
  theme=bs_theme(version=5,bootswatch="materia"),
  sidebarLayout(
    sidebarPanel(
      selectInput("sex","Select sex to filter by",choices=unique(titanic$Sex))
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Static Plot",plotOutput("plot_static")),
        tabPanel("Interactive Plot",plotlyOutput("plot_interactive")),
        tabPanel("Interactive Table",dataTableOutput("table"))
      )
    )
  )
)
```

### Server

```{r}
server <- function(input,output) {
  titanic_temp <- reactive({
    titanic_temp <- titanic %>% filter(Sex==input$sex)
  })
  
  output$plot_static <- renderPlot({
    titanic_temp() %>%
      ggplot(aes(x=Age,y=Fare,color=Sex)) + geom_point()
  })
  
  output$plot_interactive <- renderPlotly({
    titanic_temp() %>%
      ggplot(aes(x=Age,y=Fare,color=Sex)) + geom_point()
  })
  
  output$table <- renderDataTable({
    titanic_temp()
  })
}
```

### Run App

```{r}
shinyApp(ui = ui, server = server)
```


